CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/redwing \
--prompt "Realistic bird with red wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/bluewing \
--prompt "Realistic bird with blue wings." \
--prompt2 "Realistic bird with red wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/greenwing \
--prompt "Realistic bird with green wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with red wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/whitewing \
--prompt "Realistic bird with white wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with red wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/purplewing \
--prompt "Realistic bird with purple wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with red wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif



CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/redwing_siwon \
--prompt "Realistic bird with red wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/bluewing_siwon \
--prompt "Realistic bird with blue wings." \
--prompt2 "Realistic bird with red wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/greenwing_siwon \
--prompt "Realistic bird with green wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with red wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/whitewing_siwon \
--prompt "Realistic bird with white wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with red wings." \
--prompt5 "Realistic bird with purple wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/bird.obj \
--output_dir results/demo/bird/purplewing_siwon \
--prompt "Realistic bird with purple wings." \
--prompt2 "Realistic bird with blue wings." \
--prompt3 "Realistic bird with green wings." \
--prompt4 "Realistic bird with white wings." \
--prompt5 "Realistic bird with red wings." \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif
