CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/blackspoiler \
--prompt Yellow sports car with black spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/redspoiler \
--prompt Yellow sports car with red spoiler.  \
--prompt2 Yellow sports car with black spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/greenspoiler \
--prompt Yellow sports car with green spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with black spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/purplespoiler \
--prompt Yellow sports car with purple spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with black spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/whitespoiler \
--prompt Yellow sports car with white spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with black spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/blackspoiler_siwon \
--prompt Yellow sports car with black spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/redspoiler_siwon \
--prompt Yellow sports car with red spoiler.  \
--prompt2 Yellow sports car with black spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/greenspoiler_siwon \
--prompt Yellow sports car with green spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with black spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/purplespoiler_siwon \
--prompt Yellow sports car with purple spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with black spoiler.  \
--prompt5 Yellow sports car with white spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/car_face64962.obj \
--output_dir results/demo/car/whitespoiler_siwon \
--prompt Yellow sports car with white spoiler.  \
--prompt2 Yellow sports car with red spoiler.  \
--prompt3 Yellow sports car with green spoiler.  \
--prompt4 Yellow sports car with purple spoiler.  \
--prompt5 Yellow sports car with black spoiler.  \
--clipmodel ViT-L/14@336px \
--normal_nerf_pe_numfreq 10  \
--init_r_and_s \
--init_roughness 0.5 \
--width 512 \
--local_percentage 0.7 \
--background 'black' \
--radius 2  \
--n_views 3 \
--material_nerf_pe_numfreq 12 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1  \
--frontview_std 12 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.01 \
--maxcrop 0.05 \
--seed 150 \
--n_iter 1501 \
--learning_rate 0.0005 \
--frontview_center 1.96349 0.6283 \
--render_gif