sh ./demo/test_siwon_bird_vitl.sh
sh ./demo/test_siwon_whale_vitl.sh
sh ./demo/test_siwon_candle_vitl.sh
sh ./demo/test_siwon_chair_vitl.sh
sh ./demo/test_siwon_dragon_vitl.sh
sh ./demo/test_siwon_horse_vitl.sh
sh ./demo/test_siwon_person_vitl.sh
sh ./demo/test_siwon_sofa_vitl.sh
sh ./demo/test_siwon_squirrel_vitl.sh
sh ./demo/test_siwon_car_vitl.sh
