CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/redsuit \
--prompt "Ironman with red suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/bluesuit \
--prompt "Ironman with blue suit." \
--prompt2 "Ironman with red suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/greensuit \
--prompt "Ironman with green suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with red suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/woodensuit \
--prompt "Ironman with wooden suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with red suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/stonesuit \
--prompt "Ironman with stone suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with red suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/redsuit_siwon \
--prompt "Ironman with red suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/bluesuit_siwon \
--prompt "Ironman with blue suit." \
--prompt2 "Ironman with red suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/greensuit_siwon \
--prompt "Ironman with green suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with red suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/woodensuit_siwon \
--prompt "Ironman with wooden suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with red suit." \
--prompt5 "Ironman with stone suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/person.obj \
--output_dir results/demo/person/stonesuit_siwon \
--prompt "Ironman with stone suit." \
--prompt2 "Ironman with blue suit." \
--prompt3 "Ironman with green suit." \
--prompt4 "Ironman with wooden suit." \
--prompt5 "Ironman with red suit." \
--clipmodel ViT-L/14@336px \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 \
--render_gif