CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/brown \
--prompt Fluffy squirrel with a reddish-brown tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/grey \
--prompt Fluffy squirrel with a grey bushy tail.  \
--prompt2 Fluffy squirrel with a reddish-brown tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/strip \
--prompt Fluffy squirrel with a striped tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a reddish-brown tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/spot \
--prompt Fluffy squirrel with a spotted tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a reddish-brown tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/black \
--prompt Fluffy squirrel with a black tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a reddish-brown tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif


CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/brown_siwon \
--prompt Fluffy squirrel with a reddish-brown tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/grey_siwon \
--prompt Fluffy squirrel with a grey bushy tail.  \
--prompt2 Fluffy squirrel with a reddish-brown tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/strip_siwon \
--prompt Fluffy squirrel with a striped tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a reddish-brown tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/spot_siwon \
--prompt Fluffy squirrel with a spotted tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a reddish-brown tail.  \
--prompt5 Fluffy squirrel with a black tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif

CUDA_VISIBLE_DEVICES=2 python eval.py  \
--obj_path data/source_meshes/squirrel.obj \
--output_dir results/demo/squirrel/black_siwon \
--prompt Fluffy squirrel with a black tail.  \
--prompt2 Fluffy squirrel with a grey bushy tail.  \
--prompt3 Fluffy squirrel with a striped tail.  \
--prompt4 Fluffy squirrel with a spotted tail.  \
--prompt5 Fluffy squirrel with a reddish-brown tail.  \
--clipmodel ViT-B/32 \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0  \
--render_gif