CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/silvertail \
--prompt Blue whale with silver tail.  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/goldentail \
--prompt Blue whale with golden tail.  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/redtail \
--prompt Blue whale with red tail.  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/greentail \
--prompt Blue whale with green tail.  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/purpletail \
--prompt Blue whale with purple tail.  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 


CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/silvertail_siwon \
--prompt "Blue whale;with silver tail"  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/goldentail_siwon \
--prompt "Blue whale;with golden tail"  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/redtail_siwon \
--prompt "Blue whale;with red tail"  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/greentail_siwon \
--prompt "Blue whale;with green tail"  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/BlueWhale.obj \
--output_dir results/demo/BlueWhale/purpletail_siwon \
--prompt "Blue whale;with purple tail"  \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0 