CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/goldenmane \
--prompt "Elegant horse with a golden mane." \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/silvermane \
--prompt "Elegant horse with a silver mane." \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/greenmane \
--prompt "Elegant horse with a green mane." \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/redmane \
--prompt "Elegant horse with a red mane." \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/blackmane \
--prompt "Elegant horse with a black mane." \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   


CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/goldenmane_siwon \
--prompt "Elegant horse;with a golden mane" \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/silvermane_siwon \
--prompt "Elegant horse;with a silver mane" \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/greenmane_siwon \
--prompt "Elegant horse;with a green mane" \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/redmane_siwon \
--prompt "Elegant horse;with a red mane" \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   

CUDA_VISIBLE_DEVICES=2 python main_siwon.py  \
--obj_path data/source_meshes/horse.obj \
--output_dir results/demo/horse/blackmane_siwon \
--prompt "Elegant horse;with a black mane" \
--width 456 --background 'black' \
--init_r_and_s  \
--init_roughness 0.7 \
--local_percentage 0.4 \
--symmetry \
--radius 2.5 \
--n_views 3 \
--material_random_pe_sigma  30 \
--material_random_pe_numfreq  256 \
--num_lgt_sgs 32 \
--n_normaugs 4 \
--n_augs 1 \
--frontview_std 2 \
--clipavg view \
--lr_decay 0.7 \
--mincrop 0.05 \
--maxcrop 0.2 \
--seed 100 \
--n_iter 1501  \
--learning_rate 0.0005 \
--frontview_center 0 0   